apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-deployment
  namespace: gitops-flux-k8s
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: flux-app
          image: guhanandan/flux-demoapp:a5dcfbcd7d28d956a0dee1a5f57a34c0c58cebee
          ports:
            - containerPort: 80
