apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-deployment
  namespace: gitops-flux-k8s
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: flux-app
          image: guhanandan/flux-demoapp:db836b91dff82216b03403faf145f02045cbbcd8
          ports:
            - containerPort: 80
