apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-deployment
  namespace: gitops-flux-k8s
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: flux-app
          image: guhanandan/flux-demoapp:4b9851d1444c16e45dd17f47ef9376f1a7227600
          ports:
            - containerPort: 80
