apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-deployment
  namespace: gitops-flux-k8s
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: flux-app
          image: guhanandan/flux-demoapp:87733f9d161adfd28c1c27c5049726d6ee31f0eb
          ports:
            - containerPort: 80
