apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: myapp-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        name: Flux Bot
        email: flux@example.com
      messageTemplate: "Update image tag to {{range .Updated.Images}}{{.NewTag}}{{end}}"
    push:
      branch: main
